language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - tar xvzf $TRAVIS_BUILD_DIR/bin/aliyun-cli-linux-3.0.2-amd64.tgz -C $TRAVIS_BUILD_DIR/bin/
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - aliyun version
script:
  - yarn install
  - npm run build
  - npm test
deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  on:
    branch: master
