language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - eval "$(gimme 1.10)"
  - go get -u github.com/aliyun/aliyun-cli
script:
  - npm run build
  - npm test
deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  on:
    branch: master
