language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - gimme stable
  - gimme list
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $GOPATH/src/github.com/aliyun
  - cd $GOPATH/src/github.com/aliyun
  - git clone http://github.com/aliyun/aliyun-cli.git
  - git clone http://github.com/aliyun/aliyun-openapi-meta.git
  - cd aliyun-cli
  - sudo make install
script:
  - npm run build
  - npm test
deploy:
  provider: script
  script: bash -x scripts/deploy.sh
  on:
    branch: master
